######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[{config.avatar}](/about/)'
  title: '[{config.title}](/)'
  subtitle: 'Calf 的自留地 · 昙花一现 | 或有月下赏花人 应无所憾'

# 侧边栏主功能导航菜单
menubar:
  columns: 4
  items:
    - id: post
      theme: '#FFA500'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: notes
      theme: '#1BCDFC'
      icon: solar:notebook-bold-duotone
      title: 笔记
      url: /notes/
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: about
      theme: '#2196F3'
      icon: solar:user-bold-duotone
      title: 关于
      url: /about/

inject:
  head:
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css">
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/source-code-pro@2.38.0/source-code-pro.min.css">

######## Article ########
article:
  license: '本文由 [Calf](/) 原创，采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'

######## Footer ########
footer:
  social:
    email:
      icon: brand:gmail
      url: mailto:calf.zhou@gmail.com
    github:
      icon: brand:github
      url: https://github.com/calfzhou
    facebook:
      icon: brand:facebook
      url: https://www.facebook.com/calfzhou
    telegram:
      icon: brand:telegram
      url: https://t.me/calfzhou
  content: |
    本站所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    Powered by [Hexo](https://hexo.io/) + [{theme.name} {theme.version}]({theme.tree}). Hosting on [GitHub Pages](https://pages.github.com/).
    Copyright © 2011-2024 [gocalf.com](/) 保留所有权利

plugins:
  animcube3:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube3.js"></script>

style:
  prefers_theme: auto # auto / light / dark
  font-size:
    root: 18px
  font-family:
    logo: '"LXGW WenKai Lite", "Helvetica Neue", Helvetica, "Lucida Grande", Lucida, Tahoma, Arial, "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", STXiHei, SimHei, sans-serif'
    body: '"LXGW WenKai Lite", "Helvetica Neue", Helvetica, "Lucida Grande", Lucida, Tahoma, Arial, "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", STXiHei, SimHei, sans-serif'
    code: '"LXGW WenKai Lite", Monaco, Menlo, Consolas, "Courier New", monospace'
    codeblock: '"Source Code Pro", Monaco, Menlo, Consolas, "Courier New", monospace'
  border-radius:
    image: revert
