######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[{config.avatar}](/about/)'
  title: '[{config.title}](/)'
  subtitle: 'Calf 的自留地 · 昙花一现 | 或有月下赏花人 应无所憾'

# 侧边栏主功能导航菜单
menubar:
  columns: 4
  items:
    - id: post
      theme: '#FFA500'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: notes
      theme: '#1BCDFC'
      icon: solar:notebook-bold-duotone
      title: 笔记
      url: /notes/
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: Wiki
      url: /wiki/
    - id: about
      theme: '#3370FF'
      icon: calf:gocalf-duotone
      title: 关于
      url: /about/

inject:
  head:
    - <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png?v=20240514">
    - <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png?v=20240507">
    - <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png?v=20240507">
    - <link rel="manifest" href="/favicon/site.webmanifest?v=20240507">
    - <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-webfont/1.7.0/style.min.css" />
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/source-code-pro@2.38.0/source-code-pro.min.css">

######## Notebook ########
notebook:
  tagcons:
    calf: calf:gocalf
    font: solar:text-linear
    game: solar:gamepad-minimalistic-bold
    git: brand:git
    it: solar:code-linear
    mac: brand:apple
    math: solar:calculator-minimalistic-linear

######## Article ########
article:
  license: '本文由 [Calf](/) 原创，采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  share: [link, wechat, email]

######## Comments ########
comments:
  service: giscus
  giscus:
    data-repo: calfzhou/gocalf.com

######## Footer ########
footer:
  social:
    email:
      icon: brand:gmail
      url: mailto:calf.zhou@gmail.com
    github:
      icon: brand:github
      url: https://github.com/calfzhou
    facebook:
      icon: brand:facebook
      url: https://www.facebook.com/calfzhou
    telegram:
      icon: brand:telegram
      url: https://t.me/calfzhou
    pgp:
      icon: other:fingerprint-duotone
      url: /pgp/
    theme:
      icon: default:theme
      onclick: 'switchTheme()'
  sitemap:
    'GoCalf':
      - '[主页](/)'
      - '[关于](/about/)'
      - '[PGP 信息](/pgp/)'
      - '[旧站](https://blog.gocalf.com/)'
    '内容':
      - '[笔记<span class="dot"></span>杂七杂八](/notes/)'
      - '[博客<span class="dot"></span>近期发布](/)'
      - '[博客<span class="dot"></span>归档](/blog/archives/)'
      - '[所有 Wiki 项目](/wiki/)'
      - '[所有笔记本](/notebooks/)'
    '联系我':
      - '[给我发邮件](mailto:calf.zhou@gmail.com)'
      - '[GitHub](https://github.com/calfzhou)'
      - '[Facebook](https://www.facebook.com/calfzhou)'
      - '[Telegram](https://t.me/calfzhou)'
    '特别感谢':
      - '[Hexo](https://hexo.io/)'
      - '[Hexo Stellar](https://xaoxuu.com/wiki/stellar/)'
      - '[霞鹜文楷](https://github.com/lxgw/LxgwWenKai)'
      - '[今日诗词](https://www.jinrishici.com/)'
  content: |
    本站所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    本站由 [Hexo](https://hexo.io/)、[{theme.name} {theme.version}]({theme.tree}) 和 [GitHub Pages](https://pages.github.com/) 强力驱动。
    Copyright © 2011-2024 [gocalf.com](/) 保留所有权利。
    <span class="jinrishici-sentence"></span>
    <script src="https://sdk.jinrishici.com/v2/browser/jinrishici.js" charset="utf-8"></script>

plugins:
  animcube3:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube3.js"></script>

style:
  prefers_theme: dark # auto / light / dark
  font-size:
    root: 18px
  font-family:
    logo: '"LXGW WenKai", "Helvetica Neue", Helvetica, "Lucida Grande", Lucida, Tahoma, Arial, "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", STXiHei, SimHei, sans-serif'
    body: '"LXGW WenKai", "Helvetica Neue", Helvetica, "Lucida Grande", Lucida, Tahoma, Arial, "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", STXiHei, SimHei, sans-serif'
    code: '"LXGW WenKai", "Source Code Pro", Monaco, Menlo, Consolas, "Courier New", monospace'
    codeblock: '"Source Code Pro", Monaco, Menlo, Consolas, "Courier New", monospace'
  border-radius:
    image: revert
